import {
  AllowSaves,
  Description,
  HacknetExtension,
  HasIntroStartup,
  IntroStartupSong,
  Language,
  Name,
  StartingActions,
  StartingMission,
  StartingTheme,
  StartsWithTutorial,
  WorkshopDescription,
  WorkshopLanguage,
  WorkshopPreviewImagePath,
  WorkshopPublishID,
  WorkshopTags,
  WorkshopVisibility,
} from "hnxml/jsx/info";
import { File } from "./file.ts";
import { render } from "./render.tsx";
import { startingAction } from "./actions.tsx";
import { startingMission } from "./missions.tsx";
import { workshopLogo } from "./assets.ts";

const description: string = `PCS OS Terminal

A Hacknet Extension generated by hnxml.js that mimics https://ak.hypergryph.com/pcs 

https://github.com/FBIKdot/PCS-OS
https://github.com/Modern-School/hnxml
`;

export const extensionInfo = new File(
  "ExtensionInfo.xml",
  render(
    <HacknetExtension>
      <AllowSaves>{"true" as const}</AllowSaves>
      <Description>{description}</Description>
      <HasIntroStartup>{"false" as const}</HasIntroStartup>
      <IntroStartupSong>bgm.a808ef.ogg</IntroStartupSong>
      <Language>{"en-us" as const}</Language>
      <Name>PCS OS</Name>
      <StartingActions>{startingAction.path}</StartingActions>
      <StartingMission>{startingMission.path}</StartingMission>
      <StartingTheme>TerminalOnlyBlack</StartingTheme>
      <StartsWithTutorial>{"false" as const}</StartsWithTutorial>
      <WorkshopDescription>{description}</WorkshopDescription>
      <WorkshopLanguage>English</WorkshopLanguage>
      <WorkshopVisibility>{"0" as const}</WorkshopVisibility>
      <WorkshopTags>Extension,hnxml</WorkshopTags>
      <WorkshopPreviewImagePath>
        {workshopLogo.target_path}
      </WorkshopPreviewImagePath>
      <WorkshopPublishID>3522802739</WorkshopPublishID>
    </HacknetExtension>,
  ),
);
